### ISSUE TITLE
Resolve Difference Between Types in Taint Analysis and Auth Logic to allow integration

### ISSUE THREAD

**Issue by aferr** [google-research/raksha#102]
The authorization logic does not use types in its souffle output (all arguments are of type `symbol`), but the taint analysis for Raksha does.

To make integration possible, we need to resolve the difference between types for the relation where they interface which is `says_downgrades`. In the `.dl` files produced by the authorization logic this is declared as

`.decl says_downgrades(x0: symbol, x1: symbol, x2: symbol)`

but in `src/analysis/souffle/authorization_logic.dl` this is declared as

`.decl says_downgrades(speaker: Principal, p: AccessPath, t: Tag)`

Here are a few ways to fix this:
1) Support types and type declarations in the authorization logic
2) (Temporarily) remove the types from the relevant parts of the taint analysis (this would ripple through to everything with AccessPath)
3) Write a script that just removes the type declarations for `says_downgrades` from the auth logic outputs so that just the declaration in `authorization_logic.dl` is used. Other relation declarations in the auth logic code should remain the same. I think that this should work, but would need to try it out.

Probably option 3) is easiest, but I figured I would ask what is preferred.

**Comment by aferr** [comment]
@bgogul @markww

**Comment by aferr** [comment]
@markww mentioned https://souffle-lang.github.io/types#type-conversion which seems potentially helpful for this
@bgogul also mentioned that it could be good to pass a file to auth logic that lists relations to skip declaring.

(wanted to just list these both before I forget)

**Comment by bgogul** [comment]
> @bgogul also mentioned that it could be good to pass a file to auth logic that lists relations to skip declaring.

This might be the simplest? You pass a list of relations names and consult it before adding any declarations to the generated dl file?
