### ISSUE TITLE
Allow `DerivesFrom` claims to be checked by authorization logic.

### ISSUE THREAD

**Issue by markww** [google-research/raksha#120]
Currently, `DerivesFrom` claims are used to draw an explicit edge between an input and an output in a `ParticleSpec` and also prevent the drawing of default edges between the inputs and outputs within the code that generates analysis Datalog facts. This, in a sense, causes `DerivesFrom` claims to always be believed. What we want is for `DerivesFrom` claims to be checked by authorization logic and, if they are not believed by authorization logic, fall back on the default dataflow edges. This may require the datalog facts generator to output `derivesFromEdge`s and `defaultIntraParticleEdge`s (not necessarily final names) which are then either turned into `edge`s or ignored depending upon the result of the authorization logic.

**Comment by bgogul** [comment]
This is obsolete as we no longer support the old arcs manifest.
