### ISSUE TITLE
Make universe-relations (`isTag`, `isAccessPath`, etc) be populated only from relations containing base facts.

### ISSUE THREAD

**Issue by markww** [google-research/raksha#126]
Throughout our datalog files, we have universe-populating relations, which contain all instances of a particular type of symbol. For instance, `isTag` contains all of the tags present in the system, `isAccessPath` contains all access paths, etc. These are useful for indicating to Souffle the universe that variables belong in, called "grounding" symbols in Datalog. Often, the entries in these rules are inferred from other relations, like so:

```Datalog
isTag(tag) :- claimHasTag(_, _, tag).
isTag(tag) :- mayHaveTag(_, tag).
```

In the above example, there is a solid reason for the first one: our datalog-generating code outputs `claimHasTag` as a base fact, and we want to gather all of the `tag`s specified in any claim without having to generate an `isTag` alongside the claim.

The second one, however, is much more dubious. `mayHaveTag` is never output directly by the datalog generation; it is inferred only from other facts (in fact, at the moment, I believe it always derives from a `claimHasTag`). This makes the grounding relation  less basic than `mayHaveTag`, and another relation that attemps to use `isTag` to ground its variables and is later used alongside `mayHaveTag` may cause a circularity.

We should go through our Datalog and either ensure that all such universe-populating rules refer only to relations containing only basic facts or eliminate them entirely and populate our universe with basic facts.

**Comment by aferr** [comment]
The authors of Souffle (Bernhard Scholz and co) seem to also write datalog with similar relations that fix inputs to a finite set such as [the A relation in this example](https://souffle.zulipchat.com/#narrow/stream/258786-Souffle/topic/Queries.20to.20test.20an.20infinite.20relation/near/213508681). We just borrowed this universe idea from the authors of Souffle. So I suspect it's reasonable to do things this way.

It seems plausible to me that this can cause rules that [for which there is no stratification (ch2.3)](http://blogs.evergreen.edu/sosw/files/2014/04/Green-Vol5-DBS-017.pdf), like you said. Though maybe we can just fix stratification issues if/when we encounter them?

**Comment by aferr** [comment]
Actually, doing away with them could also work out fine as long as in our own language we can figure out how to populate universe relations. (I think maybe our SecPal implementation does this to some extent, though I honestly can't remember).

**Comment by aferr** [comment]
Actually, removing these universe populating rules could also be OK as long as in our own language we can figure out how to populate them so that everything is stratified. (If we want to do it this way, maybe we would need to defer until we have one single language).

**Comment by markww** [comment]
I think I was a bit too down on universe relations. More experience with Souffle has taught me that a discipline of trying to populate universes close to base and input relations and limiting negations is sufficient. Closing as WONTFIX.
