### ISSUE TITLE
Investigate why authorization logic requires a specific nightly build of rust.

### ISSUE THREAD

**Issue by bgogul** [google-research/raksha#143]
Specifically, we import `rust_repositories(version = "nightly", iso_date = "2021-07-01", edition="2018")`.

**Comment by markww** [comment]
You were right, @bgogul , it wasn't just the `try_blocks` feature. It is also `antlr4rust`, see https://github.com/google-research/raksha/pull/144#discussion_r716921015 . I'm not sure that there's anything to do other than:

1. pick another Rust parser generator (there appear to be several): https://lib.rs/parsing
2. get rid of the Rust parser entirely and rewrite in C++ (this looks to be our current strategy for compatibility with other Google stuff).

**Comment by bgogul** [comment]
Marking this as obsolete as we will be removing rust implementation soon.
