### ISSUE TITLE
Ownership of access paths based on particle spec or handles

### ISSUE THREAD

**Issue by bgogul** [google-research/raksha#220]
PR #215 introduces a notion of ownership of access paths. However, they refer to access paths in an actual instance of a particle in a recipe. Therefore, we end up having to make statements like `ownsAccessPath("UserA", "R.P1#2.foo")`, where `P1#2` is an instance of particle `P1` in recipe. We should make it possible to specify ownership at the level of access path for store handles or access path of a particle spec. e.g., `ownsAccessPath("UserA", "P1.foo")`, ​`ownsAccessPath("UserA", "store1")`.

**Comment by markww** [comment]
This relates to the Raksha Arcs manifest frontend, which is now deprecated.
