### ISSUE TITLE
Create git trigger to ensure that copyright is updated correctly.

### ISSUE THREAD

**Issue by markww** [google-research/raksha#260]
It is 2022, which means we have to update all of our copyright headers as soon as we edit any file checked into Raksha. To prevent from making too much of a mess, we should create a git trigger to force us to have our copyright headers up to date when pushing any edited file.

**Comment by tiziano88** [comment]
FYI, according to go/copyright, the year is when the file was created, and must not be changed when editing, moving or copying the file.

**Comment by markww** [comment]
Whoops, it looks like I assumed the wrong policy. Thank you for setting me straight on this! Closing.
