### ISSUE TITLE
Have a way to specify the fields of an entity type in datalog

### ISSUE THREAD

**Issue by bgogul** [google-research/raksha#326]
This can be used to infer all possible access paths in datalog instead of in C++ code. See https://github.com/google-research/raksha/blob/62fced633b88553191f9b44d14bc939a627d8f3b/src/ir/types/schema.cc#L17
We can also replace the following C++ code with datalog rules:
 https://github.com/google-research/raksha/blob/62fced633b88553191f9b44d14bc939a627d8f3b/src/ir/particle_spec.cc#L47

**Comment by markww** [comment]
This is largely a concern of the Arcs manifest frontend, which is deprecated. We currently don't have a structured representation for `AccessPath`s in the IR outside of that frontend. Closing.
