### ISSUE TITLE
Visitor For Authorization Logic AST

### ISSUE THREAD

**Issue by aferr** [google-research/raksha#345]
Create a conventional visitor pattern for the authorization logic AST which is [here](https://github.com/google-research/raksha/blob/main/src/ir/auth_logic/ast.h)

**Comment by aferr** [comment]
@bgogul meant to CC you that this exists

**Comment by bgogul** [comment]
@harsha-mandadi FYI.

**Comment by aferr** [comment]
This issue is meant to track the implementation of a visitor that runs on the (already constructed objects) `ast.h`. (This is not meant to track implementing a visitor for constructing the objects in `ast.h`). A visitor would simplify some of the code that runs on the AST. The visitor pattern really shines for compiler passes where the order of the traversal does not matter much, or only a small part of the AST is relevant. For example, this is helpful for something like: "implement a function that gets the set of predicates with type number that are subexpressions of AstAssertion". (For parts of the compiler where we need to spell out the order of the AST traversal the visitor might not help as much).

There are some good uses for this in the authorization logic implementation now such as the functionality for populating type environments here: (https://github.com/google-research/raksha/blob/fa0ce4e17ee9f83eef15cbbf4de0cd090c48964d/rust/tools/authorization-logic/src/souffle/universe_translation.rs#L126). 

These issues are related:
 - [#416](https://github.com/google-research/raksha/issues/416) -- use the visitor for populating type environments.
 - #417 -- move populating type environments to a separate pass

**Comment by aferr** [comment]
This was fixed in #643
