### ISSUE TITLE
Create a helper function and/or builder for constructing a simple `merge` operation.

### ISSUE THREAD

**Issue by markww** [google-research/raksha#350]
For our first cut at integrating with the SQL analysis, we will not include rich AST information. Rather, we will map all expressions to a single `merge` operation, which shall merge the tags of its two inputs into its output. This will allow us to quickly put together an MVP showing some simple dataflow analysis. Because this is going to be the bread and butter of our representation, we should create a helper function and/or builder to make that easy in Raksha.

**Comment by bgogul** [comment]
Done in  #421 and #492
