### ISSUE TITLE
Add protos to propagate information about SQL to Raksha IR

### ISSUE THREAD

**Issue by markww** [google-research/raksha#351]
For our first cut at integrating the SQL analysis with Raksha, we will expose a limited set of Raksha features to the analysis. These will include:

* The `merge` operation (#350)
* `PolicyRule` IR structures (#349)
* `Block` builder
* `Module` builder
* `TagClaim` builder (for claiming that particular columns are confidential or have structural characteristics).

Because the SQL analysis is not in C++, we need to expose this interface across the language barrier in some way. We think Swig might be the easiest way to do this, but protos might be easier.

**Comment by bgogul** [comment]
We have the protos as well as the code for decoding the protos into our IR.
