### ISSUE TITLE
Extend `TagClaim` to allow claiming presence of `IntegrityTag`s.

### ISSUE THREAD

**Issue by markww** [google-research/raksha#354]
Currently, our `TagClaim` IR structure always introduces confidentiality tags. For integration with the SQL analysis, we need to be able to introduce integrity tags as well. This issue tracks adding that functionality to `TagClaim`.

**Comment by bgogul** [comment]
Do you want to build on top of the exisitng `TagClaim` or as part of the new IR where `TagClaim` canl be an operator?

I think it makes sense to build on top of the new IR by adding a new operator. It is prudent not to add more use cases of the IR entities that could be deprecated?

**Comment by markww** [comment]
Good point. I'll re-focus this on exposing the new `TagClaim` operator.

**Comment by markww** [comment]
Actually, I'll just close this, exposing the operator is handled by the IR-exposing issue.
