### ISSUE TITLE
Walk SQL Analysis policy rule tree to generate custom Datalog.

### ISSUE THREAD

**Issue by markww** [google-research/raksha#365]
The SQL verifier has a structure called a `PolicyRule`, which describes an AST snippet, with `IntegrityTag` prerequisites, that should cause some transformation on the tag state. Ideally, we would like to translate these rules into authorization logic queries, but for the MVP, we will just generate custom Datalog to compile into the analysis for these policy rules.

Generally, these should be of the form:

```Souffle
removeTag("someSqlAp", "defaultOwner", "tag") :- structuralMatch("ruleName", "someSqlAp", ["input1", ["input2", nil]]), hasIntegrityTag("input1", "ITag1"), hasIntegrityTag("input2", "ITag2").
```

**Comment by bgogul** [comment]
As a first step, let us manually translate one of the policies into datalog. The important thing is to get this plumbed into the analysis.
