### ISSUE TITLE
Setup Kokoro/GCB for CI Testing

### ISSUE THREAD

**Issue by bgogul** [google-research/raksha#48]
We have github actions now, but would be good to migrate to kokoro to get more resources and better logs.

**Comment by markww** [comment]
@bgogul , I think you already fixed this. I've reassigned it to you, but will let you hit the "close with comment" button so you get the associated feeling of accomplishment :)

**Comment by bgogul** [comment]
> @bgogul , I think you already fixed this. I've reassigned it to you, but will let you hit the "close with comment" button so you get the associated feeling of accomplishment :)

Thank you for the honors, @markww! :)

Fixed by #212 and #213.
