### ISSUE TITLE
Support for Comparisons on Numbers in C++ Implementation of Auth Logic

### ISSUE THREAD

**Issue by aferr** [google-research/raksha#637]
This was implemented for the rust version in #427 so this can follow that PR

**Comment by harsha-mandadi** [comment]
Andrew, we support comparison on Numbers in C++ but organized in a different way. Some tests for reference: https://github.com/google-research/raksha/blob/be6ef8e1e1a20735a06637c12db9ed0b87e3d2a2/src/ir/auth_logic/ast_construction_says_assertion_test.cc#L58

**Comment by aferr** [comment]
OK I guess when constructing the ast, rather than making a separate AST node for RValue, you make a BaseFact where the name of the predicate is the operator [here](https://github.com/google-research/raksha/blob/be6ef8e1e1a20735a06637c12db9ed0b87e3d2a2/src/ir/auth_logic/ast_construction.cc#L92).

This might work OK for now, but eventually I think it's better to have a separate AST node for RValues since if you do it this way you are throwing away the inforamation that this is a numeric comparison rather than a regular predicate. This might make the universe relation translation code slightly more awkward in one spot [namely here](https://github.com/google-research/raksha/blob/be6ef8e1e1a20735a06637c12db9ed0b87e3d2a2/rust/tools/authorization-logic/src/souffle/universe_translation.rs#L195), but I think we can work around it.

**Comment by aferr** [comment]
OK this issue was actually fixed by @harsha-mandadi a while ago. Sorry about that. My mistake.

A separate issue tracks the minor point: #672
