### ISSUE TITLE
Reduce code duplication in arcs tests

### ISSUE THREAD

**Issue by bgogul** [google-research/raksha#64]
There is so much repetition in the .arcs files present in the tests directory. e.g, the only differences between a file named `ok_blah.arcs` and `fail_blah.arcs` are a couple of claims or checks. It would nicer to unify these to avoid code duplication.

One possible solution is to have meta comments in the fashion of llvm lit. For example, we could define three different tests (`OK`, `FAIL`, `ANOTHER_TEST`) in a single file as follows:
```
particle P
  input: X
  output: Y
//OK: claim input is secure
//FAIL: claim input is public
//ANOTHER_TEST: claim input is private
```

**Comment by bgogul** [comment]
Something like `--check-prefix` in https://llvm.org/docs/CommandGuide/FileCheck.html could be useful here.

**Comment by markww** [comment]
We no longer support legacy Arcs manifests, closing.
