### ISSUE TITLE
Make entry point suitable for running Raksha analysis on a `IrTranslationUnit` from a cross-language call.

### ISSUE THREAD

**Issue by markww** [google-research/raksha#645]
The new Raksha proto implementation looks like it's in pretty good shape, but it is missing one piece to allow it to be effectively used from across the language boundary: a function that takes in a `const proto::IrTranslationUnit&` and a `Policy` as its arguments and returns an `AnalysisResult`.

We currently have the function `ProtoToIr::Convert` that takes a proto and an `IRContext` and converts it into a `Module` and an `SsaNames`. `IRContext` is default constructible, and the `Module` can easily be passed into `SoufflePolicyChecker::IsModulePolicyCompliant` alongside a `Policy`. All of this is easy to hook up on the C++ side. But it's non trivial for a cross-language client to correctly assemble these pieces.

This issue is considered resolved once such a function exists.

**Comment by Cypher1** [comment]
@markww I was wondering about the purpose of this entry point, compared to what @cromwellian has landed in #669.

Should the --proto (via text proto) go via this, or should we move text protos to use a binary proto, or are they independent in your view?

**Comment by Cypher1** [comment]
@markww Just following up on this. Is this still needed? Thanks

**Comment by markww** [comment]
My thinking around this is largely "if we wanted to do a cross language call, within the same process, without running a command on the shell, would we be able to do that?". I think that the answer is currently still no: we don't have a function that can be exposed via a wrapper generator like SWIG that someone can just pick up and run with in Java/Python/whatever.

That said, it seems like y'all are getting along just fine without it. How is that the case? Is it natural, in the ArcsJs environment, t to just spin up a new process for handling this case? If so, then this can be kicked down the read by you, @Cypher1 , unassigning yourself or even closing it as too trivial to track.

**Comment by Cypher1** [comment]
I think, for now, I'll close it as covered by our existing tooling (via text or proto representations)
