### ISSUE TITLE
Make tests comparing AST auth logic trees use `operator==` rather than equality of debug prints.

### ISSUE THREAD

**Issue by markww** [google-research/raksha#676]
In #643 , we added a visitor for the authorization logic AST. The test for this compared a large number of debug printed strings from the AST nodes, which were introduced for this purpose alone. This isn't great, as if the test fails, a reader must parse a lot of text in their heads to diagnose how the failure occurred. In addition, debug printing usually means printing for debugging, which usually does not imply any particular stability requirements for tests, making these tests 

The relevant AST nodes should be refactored to just have an `operator==` and for those tests to compared via those `operator==`. If the test fails, someone can always insert print statements or go to the debugger to discover why the test is misbehaving.

**Comment by bgogul** [comment]
I believe this is done?
