### ISSUE TITLE
Implement C++ representation of the Primitive types and EntityType in TypeProto

### ISSUE THREAD

**Issue by bgogul** [google-research/raksha#72]
See TypeProto in https://github.com/google-research/raksha/blob/3cefcebf00321e77ca6efa88448bcd644e3e34ba/third_party/arcs/proto/manifest.proto#L101

**Comment by bgogul** [comment]
@markww I believe you are already working on this?

**Comment by markww** [comment]
Yes. This is actually done except I only implemented a single primitive type, `TEXT`. Which kind of primitive type is used is actually unimportant for building `AccessPath`s, so that might be good enough for now.

**Comment by bgogul** [comment]
PRs #86, #87 have the relevant changes. 

Can we close this then?
