### ISSUE TITLE
[Authorization Logic] Look Into StructOpt for command line args

### ISSUE THREAD

**Issue by aferr** [google-research/raksha#8]
[StructOp](https://docs.rs/structopt/0.3.21/structopt/)

This is also possibly a good opportunity to make the way inputs and outputs are specified a bit more conventional.

Suggested by: @conradgrobler @tiziano88

**Comment by bMacSwigg** [comment]
I think this was done in #461 and #462 (as re-implementation of #245), so I'm marking this closed

**Comment by aferr** [comment]
Thanks @bMacSwigg for both fixing this and properly taking managing the issue :)
