### ISSUE TITLE
Create libraries hiding and grouping external absl dependencies.

### ISSUE THREAD

**Issue by markww** [google-research/raksha#85]
Abseil is broken into many subpackages, probably to help projects built for resource-constrained systems link in just the pieces they need. We are not one of those systems; we can probably afford the additional link time and/or binary size that linking in everything we need would provide and it would simplify reviews by reducing churn in our build system. This issue tracks accomplishing this by creating two packages within Raksha, `absl` and `absl_testing`, which shall just pack up Abseil headers and packages into two larger packages for use within the Raksha project.

**Comment by bgogul** [comment]
I think this is no longer applicable. We will still need to pick and choose which absl library is included. Closing this as obsolete.
